[www]
pm = ondemand
pm.max_children = 3
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
pm.max_requests = 500
pm.process_idle_timeout = 10s
pm.status_path = /eleven-status

; Otimizações de memória
php_admin_value[memory_limit] = 256M    ; Por processo
php_admin_value[max_execution_time] = 30
php_admin_flag[log_errors] = on

; Request Buffering
request_terminate_timeout = 30s
request_slowlog_timeout = 5s
slowlog = /tmp/php-fpm-slowlog.log

; Otimizações de rede
listen.backlog = 1024
