user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    map $http_x_forwarded_for $real_ip {
        "~^(?P<first_ip>[0-9\.]+)" $first_ip;
    }

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    # ver possibilidade de adaptar o $remote_user para vir o usuario autenticadoa
    log_format detailed_log_3 '[$time_local] [$real_ip] | '
                              '$status | $body_bytes_sent | '
                              '[rt: $request_time | urt: $upstream_response_time] | '
                              '"$request" | '
                              '"$http_referer" | "$http_user_agent"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
